from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

from .cast import TOTAL_SLOTS, slot_filename
from .emitters import emit_sync
from .models import Broker, LoadEvent
from .packer import pack_events
from .scenarios import SCENARIOS, build_load_specs
from .timeline import expand_loads

ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = ROOT / "data"


def main() -> None:
    specs = build_load_specs()
    events = expand_loads(specs)
    packed = pack_events(events)

    for broker in Broker:
        broker_dir = DATA_DIR / broker.value
        broker_dir.mkdir(parents=True, exist_ok=True)
        for existing in broker_dir.glob("*_sync.json"):
            existing.unlink()
        hauldesk_carriers_seen: dict[int, str] = {}
        for slot in range(TOTAL_SLOTS):
            payload = emit_sync(broker, slot, packed[broker][slot])
            if broker == Broker.HAULDESK:
                payload["carriers"] = _first_seen_or_changed_carriers(payload["carriers"], hauldesk_carriers_seen)
            path = broker_dir / slot_filename(slot)
            path.write_text(json.dumps(payload, indent=2, sort_keys=False) + "\n", encoding="utf-8")

    (DATA_DIR / "SCENARIOS.md").write_text(_manifest(specs, packed), encoding="utf-8")


def _first_seen_or_changed_carriers(rows: list[dict], seen: dict[int, str]) -> list[dict]:
    emitted: list[dict] = []
    for row in rows:
        carrier_id = row["carrier_id"]
        signature = json.dumps(row, sort_keys=True)
        if seen.get(carrier_id) != signature:
            emitted.append(row)
            seen[carrier_id] = signature
    return emitted


def _manifest(specs, packed: dict[Broker, dict[int, list[LoadEvent]]]) -> str:
    scenario_loads: dict[str, list[str]] = defaultdict(list)
    for spec in specs:
        for scenario_id in spec.scenario_ids:
            scenario_loads[scenario_id].append(spec.key)

    files_by_load: dict[str, list[str]] = defaultdict(list)
    for broker, slots in packed.items():
        for slot, events in slots.items():
            filename = f"{broker.value}/{slot_filename(slot)}"
            for event in events:
                files_by_load[event.spec.key].append(filename)

    lines = [
        "# Synthetic Data Scenarios",
        "",
        "Generated by `python -m tools.datagen.generate`. Do not hand-edit this file; change `tools/datagen/scenarios.py` instead.",
        "",
        "Each section names the behavior this corpus is meant to exercise and the sync files that carry the evidence.",
        "",
    ]

    for key, scenario in SCENARIOS.items():
        lines.extend(
            [
                f"## {scenario.title}",
                "",
                f"**Scenario key:** `{key}`",
                "",
                scenario.description,
                "",
                f"**Expected behavior:** {scenario.expected_behavior}",
                "",
                "**Loads and files:**",
                "",
            ]
        )
        for load_key in sorted(scenario_loads.get(key, [])):
            joined = ", ".join(f"`{path}`" for path in sorted(files_by_load[load_key]))
            lines.append(f"- `{load_key}`: {joined}")
        lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    main()
